name: "Compare keys from env file"
description: "This action will verify two env files and returns ok if their all keys are equals"
inputs:
  firstEnv:
    description: "First Env"
    required: true
  secondEnv:
    description: "Second Env"
    required: true
outputs:
  result: # id of output
    description: "Action Result"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  color: "blue"
  icon: "anchor"
