name: Success

on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Show Success
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: yarn install

      - name: Compare env files
        uses: andraderaul/compare-env-files@v1.0.0
        with:
          firstEnv: .env.local
          secondEnv: .env.local

      - name: Result
        run: echo "${{ steps.outputs.result }} attack"
